const command_names = [
    'system/register_for_change_events'
  , 'system/check_account'
  , 'system/sign_in'
  , 'system/sign_out'
  , 'system/heart_beat'
  , 'player/get_players'
  , 'player/get_player_info'
  , 'player/get_play_state'
  , 'player/set_play_state'
  , 'player/get_now_playing_media'
  , 'player/get_volume'
  , 'player/set_volume'
  , 'player/volume_up'
  , 'player/volume_down'
  , 'player/get_mute'
  , 'player/set_mute'
  , 'player/toggle_mute'
  , 'player/get_play_mode'
  , 'player/set_play_mode'
  , 'player/get_queue'
  , 'player/play_queue'
  , 'player/remove_from_queue'
  , 'player/save_queue'
  , 'player/clear_queue'
  , 'player/move_queue_item'
  , 'player/play_next'
  , 'player/play_previous'
  , 'player/get_music_sources'
  , 'player/get_source_info'
  , 'browse/browse'
  , 'browse/browse'
  , 'player/get_search_criteria'
  , 'browse/search'
  , 'browse/play_stream'
  , 'browse/play_preset'
  , 'browse/play_input'
  , 'browse/play_stream'
  , 'browse/add_to_queue'
  , 'browse/add_to_queue'
  , 'browse/rename_playlist'
  , 'browse/delete_playlist'
  , 'browse/retrieve_metadata'
  , 'browse/set_service_option'
]

module.exports = {
  get command_names () {
    return command_names.slice ()
  }
}
